# Generated by Django 3.2.18 on 2023-05-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admodel',
            name='body',
            field=models.CharField(max_length=16384),
        ),
    ]
